name: Go Tests

on:
  push: # déclenche sur chaque push
    branches:
      - main
  pull_request: # déclenche aussi sur chaque PR
  workflow_dispatch: # permet de lancer manuellement

jobs:
  test:
    runs-on: ubuntu-latest # runner Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Récupère le code source

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
        # Installe Go

      - name: Run unit tests
        run: go test ./... -v
        # Lance tous les tests du projet avec détails (-v)
